### ISSUE TITLE
StaleElementReferenceException: can selenide help here?

### ISSUE THREAD

**Issue by dmak** [codeborne/selenide#158]
Consider the following situation:

* There is some section on HTML page that is updated by setting the inner HTML to some value.
* Suppose some selenide selector references the element within that section.

Now from time to time `org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM` is thrown. This happens because selector is referencing DOM element which was removed from the tree. But it does not mean has not shortly re-appeared in DOM.

How selenide can help: If `StaleElementReferenceException` then still wait for given (internal or explicit) timeout until element re-appears on the page. If it does not appear, then throw this exception (or alternatively `ElementNotFound`).

**Comment by asolntsev** [comment]
Can you provide a full stack trace of your `StaleElementReferenceException`?
I believe Selenide should automatically resolve such issue. It should be considered as a Selenide bug.

**Comment by dmak** [comment]
Here comes the stacktrace:

    testComparisonResults(org.test.ComparisonResultsTest)  Time elapsed: 8.626 sec  <<< ERROR!
    org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
    Command duration or timeout: 11 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: 'EPO-JNJJJ5J', ip: '10.3.3.127', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_55'
    Session ID: 86e1fe02-478a-4668-9f37-b98b4d5deec4
    Driver info: org.test.FirefoxDriverProvider$DisplayAwareFirefoxDriver
    Capabilities [{platform=WINDOWS, databaseEnabled=true, cssSelectorsEnabled=true, javascriptEnabled=true, acceptSslCerts=true, handlesAlerts=true, browserName=firefox, webStorageEnabled=true, nativeEvents=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
    	at com.codeborne.selenide.Selenide.executeJavaScript(Selenide.java:303)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.fireEvent(AbstractSelenideElement.java:369)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.setValue(AbstractSelenideElement.java:344)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:49)
    	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:19)
    	at com.sun.proxy.$Proxy5.val(Unknown Source)
    	at org.test.ComparisonResultsTest.testComparisonResults(ComparisonResultsTest.java:497)

**Comment by asolntsev** [comment]
@dmak It's a [bug #153](https://github.com/codeborne/selenide/issues/153) in Selenide.
It was recently fixed in Selenide 2.16. Please upgrade to Selenide 2.16

**Comment by dmak** [comment]
I have upgraded from 2.14 to 2.16 and now the issue has gone. At least I couldn't observe it for passed two days. Thanks!

**Comment by dmak** [comment]
Unfortunately I got this exception again:

    org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
    Command duration or timeout: 12 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
    System info: host: 'luu128d', ip: '10.14.1.85', os.name: 'Linux', os.arch: 'amd64', os.version: '3.0.93-0.8.2.6039.1.PTF-default', java.version: '1.7.0_25'
    Session ID: 0ce107a4-9b01-4e46-8035-f5afa4ec022e
    Driver info: org.test.integration.FirefoxDriverProvider$DisplayAwareFirefoxDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.4.0}]
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.setValue(AbstractSelenideElement.java:369)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatch(AbstractSelenideElement.java:75)
    	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:55)
    	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:19)
    	at com.sun.proxy.$Proxy6.val(Unknown Source)
    	at org.test.ComparisonResultsTest.testComparisonResults(ComparisonResultsTest.java:520)

**Comment by asolntsev** [comment]
It means that your element disappears after executing `clear()` method on it.

Look how method `$.val()` is implemented:
```java
      element.clear();
      element.sendKeys(text);
```

If the element disappears after executing `clear()` method, then you get `StaleElementReferenceException`. But what is expected behaviour? I guess you would get some exception anyway.

**Comment by dmak** [comment]
I think that for user of API, `val()` should be an atomic operation: so it either succeeds as a whole, or fails. So I think it should retry, e.g. repeat from step `waitForElement()` in case of `StaleElementReferenceException`. Finally the result can only be `ElementNotFound` (after timeout expires) or success (value was set).

It could be the case that the value was set, but shortly afterwards the element was removed. But this situation will be clearly seen if test code continues with `element.shouldHave(value("zzz"));`.

**Comment by asolntsev** [comment]
Yes, I agree that `$.val()` should be an atomic operation. But in your case, it means that you would get `ElementNotFound` exception instead of `StaleElementReferenceException`. Does it really help you?

**Comment by dmak** [comment]
In meanwhile I got this exception in another place:

    com.codeborne.selenide.ex.ListSizeMismatch: : expected: 5, actual: 0, collection: a.timeline-event-label.filter(not(css class))
    Elements: [not loaded yet...]
    Timeout: 4 s.
    Caused by: org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
    Command duration or timeout: 324 milliseconds
    Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
    System info: host: 'luu128d', ip: '10.14.1.85', os.name: 'Linux', os.arch: 'amd64', os.version: '3.0.93-0.8.2.6039.1.PTF-default', java.version: '1.7.0_25'
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.4.0}]
    	at com.codeborne.selenide.collections.ListSize.fail(ListSize.java:24)
    	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:84)
    	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:49)
    	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:42)
    	at com.codeborne.selenide.ElementsCollection.shouldHaveSize(ElementsCollection.java:27)
    	at test.TimelineTest.verifyPointEventsForLastFilter(TimelineTest.java:81)

I have considered what you say and I feel there are pros and cons. Let's some back to the example from my previous post, which I extend a bit for clarity:
`textArea.val(textToSet);` (A)
`someButton.click()` (B)
`textArea.shouldHave(value(textToSet));` (C)

Step (B) is some action, that causes the given `textArea` to be temporary removed from DOM and then added back with same value (I agree that looks ugly but that is the reality, which perhaps should be improved).
First of all, I repeat that in majority of runs the test passes fine. In left over "bad" cases it fails either in point (A) with `StaleElementReferenceException` and or in (C) because of unmet condition. From one side this is unhandy, because these two errors seems to be unrelated and the preference is that (A) never fails e.g. fail at point (C) should be consistent. However from another side this fail at (A) gives me a hint that `val()` does not complete before (B), e.g. it continues to send value character by character, but then suddenly text area is removed. And that is very disappointing.

**Comment by asolntsev** [comment]
ok, thank you. It needs deeper investigation...

**Comment by asolntsev** [comment]
@dmak 
Unfortunately I cannot investigate it during next 1.5 weeks because I am preparing for SeleniumCamp conference. Meanwhile, I suggest that you should report a bug to your developers. It seems to be incorrect application behaviour to me.

**Comment by dmak** [comment]
I leave on vacations for a week and then we have a release of the application, so I am myself fully packed. I suggest to leave this issue for a while because I think it needs further observation.

**Comment by BadNews87** [comment]
Hello there Andrei. I've experienced this type of issue testing my application too. I'm working with Firefox 34.0 and Selenium WebDriver 2.44.0 and Selenide 2.17. The problem occurs when I'm dealing with AJAX on the Web page. Selenide is locating the element and trying to click it but it gets this exception. Everything happens in milliseconds so very quick. I think I have the same case of events as Dmitry.
The element is located, AJAX refreshes it and when Selenide clicks it the exception pops up.

org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
Command duration or timeout: 7 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'MH-MacBook-Pro.local', ip: '10.216.99.89', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=34.0.5, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 5f0e03b9-628d-9349-abab-d35067613ee6
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
 at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
 at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
 at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
 at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
 at com.codeborne.selenide.impl.AbstractSelenideElement.click(AbstractSelenideElement.java:334)
 at com.codeborne.selenide.impl.AbstractSelenideElement.dispatch(AbstractSelenideElement.java:233)
 at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:67)
 at com.codeborne.selenide.impl.CollectionElement.invoke(CollectionElement.java:13)
 at com.sun.proxy.$Proxy12.click(Unknown Source)
 
...
Caused by: org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'MH-MacBook-Pro.local', ip: '10.216.99.89', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_40'
Driver info: driver.version: unknown
 at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8332:24)
 at <anonymous class>.Utils.getElementAt(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:7922:10)
 at <anonymous class>.fxdriver.preconditions.visible(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8957:11)
 at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11618:15)
 at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11635:11)
 at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11640:7)
 at <anonymous class>.DelayedCommand.prototype.execute/<(file:///var/folders/x_/71cvwpy50h57y5l38py24_x80000gq/T/anonymous1506965292166356922webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11582:5)


Is there a way that this can be corrected?

**Comment by asolntsev** [comment]
Yes, I believe this is the same problem. Working on it. We plan to deliver fixed selenide version soon.

Sent from my HTC

----- Reply message -----

**Comment by BadNews87** [comment]
How's that new Selenide version coming? Is there any specific release date set for the new version? I hope to get rid of this exception soon because it's corrupting my tests.

**Comment by asolntsev** [comment]
Hi!
Yes, we plan to release next Selenide version in April.

2015-04-15 2:40 GMT+08:00, BadNews87 <notifications@github.com>:
> How's that new Selenide version coming? Is there any specific release date
> set for the new version? I hope to get rid of this exception soon because
> it's corrupting my tests.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/codeborne/selenide/issues/158#issuecomment-93013123


-- 
Andrei Solntsev

**Comment by asolntsev** [comment]
fixed in Selenide 2.18 - coming soon

**Comment by BadNews87** [comment]
Sweet. I'll check it out & give you feedback.

**Comment by asolntsev** [comment]
Yes, please find the latest built jar at this URL:
https://oss.sonatype.org/content/repositories/snapshots/com/codeborne/selenide/2.18-SNAPSHOT/

use version `selenide-2.18-20150425.183531-11.jar` or later.

**Comment by dmak** [comment]
I have switched to v2.18, but I still get `StaleElementReferenceException`. The message says `Element belongs to a different frame` but I think it is misleading, as the only option is that given element was unattached from DOM. In this case Selenide should re-try to acquire new element from DOM and re-check the condition.
```
com.codeborne.selenide.ex.ElementNotFound: Element not found {StaleElementReferenceException: Element belongs to a different frame than the current one - switch to its containing frame to use it}
Expected: exist
Timeout: 4 s.
Caused by: StaleElementReferenceException: Element belongs to a different frame than the current one - switch to its containing frame to use it
	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:122)
	at com.codeborne.selenide.Condition.hasClass(Condition.java:397)
	at com.codeborne.selenide.Condition$13.apply(Condition.java:424)
	at com.codeborne.selenide.impl.AbstractSelenideElement.matches(AbstractSelenideElement.java:334)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:223)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:94)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:65)
	at com.codeborne.selenide.impl.WebElementProxy.invoke(WebElementProxy.java:9)
	at com.sun.proxy.$Proxy7.has(Unknown Source)
	at integration.ReportTest.reportRowsForFilter(ReportTest.java:89)
	at integration.ReportTest.verifyReportFilter(ReportTest.java:73)
	at integration.ReportTest.testReportFiltering_314(ReportTest.java:138)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element belongs to a different frame than the current one - switch to its containing frame to use it
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'WIN', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_55'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8959)
	at <anonymous class>.Utils.getElementAt(file:///C:/Users/DK83146/AppData/Local/Temp/anonymous3789333984244440402webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8546)
	at <anonymous class>.WebElement.getElementAttribute(file:///C:/Users/DK83146/AppData/Local/Temp/anonymous3789333984244440402webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11746)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/DK83146/AppData/Local/Temp/anonymous3789333984244440402webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/DK83146/AppData/Local/Temp/anonymous3789333984244440402webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12279)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/DK83146/AppData/Local/Temp/anonymous3789333984244440402webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12221)
```

**Comment by asolntsev** [comment]
As I read the error message, it clearly says that "StaleElementException"
happened because the element is found in another frame:

> Element belongs to a different frame than the current one - switch to its
> containing frame to use it}


I understand the correct solution is to switch to this frame.

2015-05-27 16:22 GMT+03:00 Dmitry Katsubo <notifications@github.com>:

> Element belongs to a different frame than the current one - switch to its
> containing frame to use it}


Andrei Solntsev

**Comment by luanyusky** [comment]
My solution is to add **element.visible(true);** 
I guess webdriver will cache the page elements, but when you change some element's value, the page refreshed, then the dom changed. you need to use some methods to add the element that you want.
